### ISSUE TITLE
Error when installing via NPM

### ISSUE THREAD

**Issue by etavener** [gammastream/scully-plugins#10]
I get the following error when I install your lib. It only recently started.

Error: Cannot find module 'fast-xml-parser'

**Comment by msacket** [comment]
I made a mistake in my npm package dependencies.  I declared it as a `devDependency` instead of a `peerDependency`.  At least I think that's the way it should be.  The angular library complains if I declare it as simply a `dependency`.  In any case, it is required.  `npm install --save-dev fast-xml-parser` should get you going.

**Comment by pegaltier** [comment]
I got the same issue for two packages:
- xmlbuilder
- fast-xml-parser

Indeed it works if i add the dependencies manually but please i would like to remove it when it will be fixed and added to peerDependency. Thanks

**Comment by msacket** [comment]
I believe I have this resolved by defining the proper peer dependencies in version 1.0.2.  If I am mistaken, reopen this and I'll take another look.

**Comment by peterpeterparker** [comment]
just installed version  `1.0.5` and  same issue still seems to happen when running scully:

> ⠹ Error: Cannot find module 'fast-xml-parser'

**Comment by msacket** [comment]
`fast-xml-parser` is a peer dependency so you have to install it yourself.  It should be telling you this when you install.  

![image](https://user-images.githubusercontent.com/10793149/101181424-7d093a00-3612-11eb-8d09-14749c142820.png)


`npm install --save-dev fast-xml-parser`

**Comment by peterpeterparker** [comment]
oki doki thx for the feedback
